<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: July 7th at 4:22pm
 */
namespace Kendo\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class AccessRuleSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'rules_class',
  1 => 'resource',
  2 => 'operation',
  3 => 'operation_label',
  4 => 'description',
);
    public static $column_hash = array (
  'rules_class' => 1,
  'resource' => 1,
  'operation' => 1,
  'operation_label' => 1,
  'description' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'rules_class',
  1 => 'resource',
  2 => 'operation',
  3 => 'operation_label',
  4 => 'description',
);

    const schema_class = 'Kendo\\Model\\AccessRuleSchema';
    const collection_class = 'Kendo\\Model\\AccessRuleCollection';
    const model_class = 'Kendo\\Model\\AccessRule';
    const model_name = 'AccessRule';
    const model_namespace = 'Kendo\\Model';
    const primary_key = NULL;
    const table = 'access_rules';
    const label = 'AccessRule';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'rules_class' => array( 
      'name' => 'rules_class',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 64,
        ),
    ),
  'resource' => array( 
      'name' => 'resource',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 64,
        ),
    ),
  'operation' => array( 
      'name' => 'operation',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 64,
        ),
    ),
  'operation_label' => array( 
      'name' => 'operation_label',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 128,
        ),
    ),
  'description' => array( 
      'name' => 'description',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'text',
          'primary' => NULL,
        ),
    ),
);
        $this->columnNames     = array( 
  'rules_class',
  'resource',
  'operation',
  'operation_label',
  'description',
);
        $this->primaryKey      = NULL;
        $this->table           = 'access_rules';
        $this->modelClass      = 'Kendo\\Model\\AccessRule';
        $this->collectionClass = 'Kendo\\Model\\AccessRuleCollection';
        $this->label           = 'AccessRule';
        $this->relations       = array( 
  'control' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Kendo\\Model\\AccessRuleSchema',
      'self_column' => 'id',
      'foreign_schema' => 'Kendo\\Model\\AccessControlSchema',
      'foreign_column' => 'rule_id',
    ),
  'accessor' => 'control',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
  'resource' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Kendo\\Model\\AccessRuleSchema',
      'self_column' => 'resource',
      'foreign_schema' => 'Kendo\\Model\\AccessResourceSchema',
      'foreign_column' => 'name',
    ),
  'accessor' => 'resource',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('AccessRule');
    }

}
