<?php
/**
 * THIS FILE IS AUTO-GENERATED BY LAZYRECORD,
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY.
 * 
 * Last Modified: August 11th at 12:35pm
 */
namespace Kendo\Model;


use LazyRecord;
use LazyRecord\Schema\RuntimeSchema;
use LazyRecord\Schema\Relationship;

class AccessRuleSchemaProxy extends RuntimeSchema
{

    public static $column_names = array (
  0 => 'actor_id',
  1 => 'role_id',
  2 => 'actor_record_id',
  3 => 'resource_id',
  4 => 'resource_record_id',
  5 => 'operation',
  6 => 'operation_label',
);
    public static $column_hash = array (
  'actor_id' => 1,
  'role_id' => 1,
  'actor_record_id' => 1,
  'resource_id' => 1,
  'resource_record_id' => 1,
  'operation' => 1,
  'operation_label' => 1,
);
    public static $mixin_classes = array (
);
    public static $column_names_include_virtual = array (
  0 => 'actor_id',
  1 => 'role_id',
  2 => 'actor_record_id',
  3 => 'resource_id',
  4 => 'resource_record_id',
  5 => 'operation',
  6 => 'operation_label',
);

    const schema_class = 'Kendo\\Model\\AccessRuleSchema';
    const collection_class = 'Kendo\\Model\\AccessRuleCollection';
    const model_class = 'Kendo\\Model\\AccessRule';
    const model_name = 'AccessRule';
    const model_namespace = 'Kendo\\Model';
    const primary_key = NULL;
    const table = 'access_rules';
    const label = 'AccessRule';

    public function __construct()
    {
        /** columns might have closure, so it can not be const */
        $this->columnData      = array( 
  'actor_id' => array( 
      'name' => 'actor_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
          'refer' => 'Kendo\\Model\\ActorSchema',
        ),
    ),
  'role_id' => array( 
      'name' => 'role_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
          'refer' => 'Kendo\\Model\\RoleSchema',
        ),
    ),
  'actor_record_id' => array( 
      'name' => 'actor_record_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'resource_id' => array( 
      'name' => 'resource_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'resource_record_id' => array( 
      'name' => 'resource_record_id',
      'attributes' => array( 
          'isa' => 'int',
          'type' => 'int',
          'primary' => NULL,
        ),
    ),
  'operation' => array( 
      'name' => 'operation',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 64,
        ),
    ),
  'operation_label' => array( 
      'name' => 'operation_label',
      'attributes' => array( 
          'isa' => 'str',
          'type' => 'varchar',
          'primary' => NULL,
          'length' => 128,
        ),
    ),
);
        $this->columnNames     = array( 
  'actor_id',
  'role_id',
  'actor_record_id',
  'resource_id',
  'resource_record_id',
  'operation',
  'operation_label',
);
        $this->primaryKey      = NULL;
        $this->table           = 'access_rules';
        $this->modelClass      = 'Kendo\\Model\\AccessRule';
        $this->collectionClass = 'Kendo\\Model\\AccessRuleCollection';
        $this->label           = 'AccessRule';
        $this->relations       = array( 
  'resource' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Kendo\\Model\\AccessRuleSchema',
      'self_column' => 'resource_id',
      'foreign_schema' => 'Kendo\\Model\\ResourceSchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'resource',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
  'actor' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Kendo\\Model\\AccessRuleSchema',
      'self_column' => 'actor_id',
      'foreign_schema' => 'Kendo\\Model\\ActorSchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'actor',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
  'role' => \LazyRecord\Schema\Relationship::__set_state(array( 
  'data' => array( 
      'type' => 3,
      'self_schema' => 'Kendo\\Model\\AccessRuleSchema',
      'self_column' => 'role_id',
      'foreign_schema' => 'Kendo\\Model\\RoleSchema',
      'foreign_column' => 'id',
    ),
  'accessor' => 'role',
  'where' => NULL,
  'orderBy' => array( 
    ),
)),
);
        $this->readSourceId    = 'default';
        $this->writeSourceId    = 'default';
        parent::__construct();
    }


    /**
     * Code block for message id parser.
     */
    private function __() {
        _('AccessRule');
    }

}
