---
bootstrap:
  - vendor/autoload.php
schema:
  auto_id: 1
  paths:
  - src/Kendo/Model
seeds:
data_source:
  default: "sqlite"
  nodes:
    sqlite:
      driver: "sqlite"
      dsn: 'sqlite::memory:'
    mysql:
      driver: mysql
      host: localhost
      database: kendo
      user: root
